### ISSUE TITLE
Notice: Undefined variable: image in

### ISSUE THREAD

**Issue by ghost** [yanniks/shariff-wordpress#3]
Hallo,
ich habe mit der letzten Version des Shariff-Wordpress-Plugins ein Problem und zwar wird mir im Frontend dieses angezeigt:

```
Notice: Undefined variable: image in /www/htdocs/xxxxxxx/wp-content/plugins/shariff-sharing/shariff-wp.php on line 92

Notice: Undefined variable: content2 in /www/htdocs/xxxxxx/wp-content/plugins/shariff-sharing/shariff-wp.php on line 101
```

Wie kann man es beheben? Ich habe PHP 5.6, letzte mySQL-Version und Wordpress 4.3.1, sowie die letzte Shariff-Wordpress-Plugun-Version von Github.

Danke euch im Vorfeld für die baldige Hilfestellung.

**Comment by yanniks** [comment]
Ich habe mich mangels Zeit dazu entschieden, die Entwicklung an meiner Shariff-Version einzustellen. Daher empfehle ich dir, auf [dieses](http://wordpress.org/plugins/shariff/) Plugin umzusteigen.

**Comment by ghost** [comment]
Vielen Dank für deine schnelle Antwort und gut, dann steige ich gleich um. Ich habe das Plugin nämlich auch gesichtet, dachte nur, deines einzusetzen.
